### ISSUE TITLE
I can't find API for authentication.

### ISSUE THREAD

**Issue by seriyvolk83** [forcedotcom/SalesforceMobileSDK-iOS-Distribution#85]
I need to create a custom iOS screen for entering username/password and process authentication. However, I cannot find the API for: 1) check if the user is already authenticated, 2) send authentication request with username/password provided. 
The suggested default web screen for signing in is ready ugly. How can I use the API from SDK to authenticate programmatically?

**Comment by bhariharan** [comment]
@seriyvolk83 Short answer - you can't. ```Salesforce``` doesn't provide an API to perform native username-password authentication that returns a refresh token. This is for security reasons, which is why we display the login screen within a ```UIWebView```. For questions/issues that are not bugs on the ```Mobile SDK```, please use our [Google+ Community](https://plus.google.com/u/1/communities/114225252149514546445). This forum is reserved for known bugs in the ```Mobile SDK```.
